### ISSUE TITLE
Is asking for 24 articles too much?

### ISSUE THREAD

**Issue by george-b** [vim-advent-calendar/vimways.org#79]
It seems we'll be even shorter on articles this year despite opening calls for papers earlier than last year. Would it make more sense to move to a "12 days of Xmas" analogue asking for 12 articles rather than the current 24? I understand this project was inspired by [24ways](https://24ways.org/) but it would appear we can't generate that amount of content.

**Comment by alerque** [comment]
When and where did the call for contributions go out?

**Comment by romainl** [comment]
The CFP was started [seven months ago](https://www.reddit.com/r/vim/comments/bj8hmk/vimways_2019_call_for_paper/) and "officially ended last months.

Indeed we seem to be unable to attract enough authors. I will probably cancel this year's edition.

**Comment by swalladge** [comment]
@romainl Are there enough articles in progress to run it as a 12 days of xmas instead of 24 as OP suggested? It seems a shame to cancel it altogether if there are already articles in the pipeline.

**Comment by alerque** [comment]
I suppose I just don't hang out in the right places. I had this repo watched from last year, and started wondering how to contribute, but Reddit isn't my gig and even poking around here I wasn't too sure whether it was open for contributions. I see now that's not the case, but I would suggest for next year a bit more "recruiting" verbiage be scattered around all the places people might bump into the project.

**Comment by romainl** [comment]
That 12 days idea seems to be a good compromise. I will have to do some retconning but hopefully it will help keep this thing going.

@alerque, I posted about the CFP on Reddit, Twitter, and Hacker News. If you have ideas for other channels I will gladly take them. And now that I think about it, the vim_use mailing list is one I missed stupidly.

**Comment by lieryan** [comment]
IMO, the main problem here is this:

> - Length-wise, anything above 1,500 words is fine.

A 1500 words article is about three pages long, which is quite a massive tome for typical internet articles and would also be time consuming to review as well.

This explicitly stated hard limit likely scares off many potential contributors which probably would be able to actually reach 1500 words anyway once they had actually started writing and once they received suggestions by reviewers on where they can expand the topics. The word limit also limited the choices of topics as there are not a lot of interesting topics that can fill up 1500 words without becoming too boring or repetitive.

I think, for next year, reducing the word count limit would make it easier for contributors to start writing. It probably also makes sense to have different quotas for the different sizes of articles, e.g. small (10 x 500 words), medium (10 x 1000 words), large (4 x 1500 words). The larger articles can be published on the weekends while the smaller ones during the weekdays, and if we received more articles than days, the smaller articles can be bundled together for a single day. It would also be easier to fill the larger quota articles if we had some choices of smaller starter articles that can be expanded, rather than planning for a large article from the start.

I don't think having lengthy deadlines would necessarily be a good thing. There are many researches showing how, paradoxically, longer deadlines can actually worsen procrastination. While not being rushed to write is a good thing, at some point, having longer calls just means that people don't feel the urgency to contribute, and once they ignore and forgot about it, the deadline would've ended before people realised it.

**Comment by romainl** [comment]
@lieryan, all good points, especially the one about quotas. But it's not the main issue, in my opinion.

Outreach is a bigger problem. The community is scattered and it is not an easy task (from my POV, at least) to spread the word evenly. r/vim is popular but the majority of its readers has very limited skills and it seems very US-centric. Twitter is more "international" but the general level seems even lower than on Reddit. Hacker News doesn't work *at all*. The intelligentsia (Drew Neil, Tim Pope, etc.) either didn't notice the project or doesn't care. The ambitious newcomers already publish on Medium or build their brand their own blogs. I went to a meetup a few weeks ago here in Paris and that was the first time everyone heard about Vimways. Then there are the few less visible but skilled users… that show interest for the project but have other priorities anyway.

**Comment by pabloariasal** [comment]
So, any news on what is going to happen? The _12 nights before Christmas theme_ seems like a pretty good format. I agree with OP in the fact that the number of requested articles is way too high, maybe 12, but high quality and carefully reviewed articles can be more convenient for next years.

**Comment by romainl** [comment]
@pabloariasal I will go with the "12 *days*" concept but they are the 12 days *after* Christmas (https://en.wikipedia.org/wiki/Twelve_Days_of_Christmas). This means a first article posted on 25 December and the last one posted on 5 January. I'm still wondering if we can get a sense of increasing value (as in https://en.wikipedia.org/wiki/The_Twelve_Days_of_Christmas_(song)) or not. I'm not sure I want to introduce that kind of notion.

I agree that 12 great articles is easier to get than 24.

**Comment by swalladge** [comment]
How many articles are in the pipeline likely to be ready for then?

I'd like to write an article - I have a half baked plan about using vim for personal wikis and note taking. Would that be interesting or useful for this run?

December 9, 2019 10:50:08 AM UTC Romain Lafourcade <notifications@github.com> kirjoitti:
>@pabloariasal I will go with the "12 *days*" concept but they are the
>12 days *after* Christmas
>(https://en.wikipedia.org/wiki/Twelve_Days_of_Christmas). This means a
>first article posted on 25 December and the last one posted on 5
>January. I'm still wondering if we can get a sense of increasing value
>(as in
>https://en.wikipedia.org/wiki/The_Twelve_Days_of_Christmas_(song)) or
>not. I'm not sure I want to introduce that kind of notion.
>
>I agree that 12 great articles is easier to get than 24.

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by romainl** [comment]
@swalladge We have 11 articles in the pipe. Among those, two are by me (a two-parts article) and three are by @george-b. If you are up for it I would really like you to write one.

**Comment by hauleth** [comment]
Shouldn't we start publishing 2019 edition now?

**Comment by swalladge** [comment]
@hauleth I think the first article will be published on 25th - cf [comment](https://github.com/vim-advent-calendar/vimways.org/issues/79#issuecomment-563178026)

**Comment by romainl** [comment]
I'm currently ill so I can't do much right now. As soon as I'm out of my bronchitis + conjunctivitis combo I will:

- make a few changes to the site templates so that it conforms to our new numbering scheme for 2019 while staying the same for 2018
- finish my articles
- do some editing on the articles we have

**Comment by george-b** [comment]
Closing this as articles are starting to be published.

Many thanks to @romainl for running this, hope you're feeling better!
