### ISSUE TITLE
Add a bit of context to "Making Things Flow"

### ISSUE THREAD

**Issue by romainl** [vim-advent-calendar/vimways.org#89]
From justinmk on reddit:

> the first paragraph of "Getting into the groove" links to a gist(s) without any explanation and the reader is expected to go look at the gist. That makes the article less portable/self-contained.

@george-b could you look into it?

**Comment by george-b** [comment]
When I wrote the article I wanted to minimise code snippets and focus on the idea of flows as to promote thought on the subject rather than copy/pasting. So I'm not really sold on the idea of making every article self-contained. I also stand by the sentence encouraging the reader to review the write-up in your gist as it's a good read.

That said here's a quick diff of a minor edit.

```diff
diff --git a/content/2019/Making-things-flow/index.md b/content/2019/Making-things-flow/index.md
index ce30665..dfa3a8d 100644
--- a/content/2019/Making-things-flow/index.md
+++ b/content/2019/Making-things-flow/index.md
@@ -35,7 +35,7 @@ The comment explains the what's being done in the `autocmd` so I won't talk abou
 
 ## Getting into the groove
 
-Whilst having been a Vim user for some time my first real exposure to the idea of curving Vim's behaviour in a transparent way was this excellent [gist][CCR]. I thoroughly recommend reading through it then coming back here. I actually even made my own [variant][Autoreply].
+Whilst having been a Vim user for some time my first real exposure to the idea of curving Vim's behaviour in a transparent way was this excellent [gist][CCR]. I actually even made my own [variant][Autoreply]. I thoroughly recommend reading through it then coming back here, but in essence the idea is that after executing certain ex-commands it is highly likely another will follow based on the output of the previous. As such populate the command-line as to minimise the typing input from the user.
 
 In any case the effect is the same. Vim's behaviour is altered not because of a setting but because we've scripted a flow. It's something we can use a great deal but we've only ever had to think about it once, when we wrote the script. To contrast we don't have to think "Oh I have a mapping that will show me X and prompt for Y", instead we ask Vim for X as usual it now prompts for Y.
```

If you think it should include more code snippets I'll add my "Autoreply" variant of your gist (I think it reads a little easier but I'm biased). If so the section around `hlsearch` would then be the only part not containing a code snippet in which case I'd then be inclined to copy purpleP's example that is currently linked too.

**Comment by george-b** [comment]
I was just going through old items I had open in GitHub and I think this can be closed.

With hindsight I'd probably re-write some of my articles but I don't think it would be of much value as for whatever reason Vimways sadly didn't seem to gather much traction with contributors. Nonetheless thank you for organizing!

**Comment by romainl** [comment]
Not much contributor love and not much reader love either. ¯\_(ツ)_/¯
